In [2]:
import numpy as np
import pandas as pd

# settings
np.random.seed(12345)
# pd.options.display.float_format = '{:,.2f}'.format # printing format
np.set_printoptions(precision=4, suppress=True) # printing format

# 5.1 Introduction to pandas Data Structures  

## 5.1.1 Series

In [3]:
# a Series is a one-dimensional array-like object 
# containing a sequence of values and an associated array of data labels, called its 'index'

obj = pd.Series([4, 7, -5, 3])
print(obj)
print('----------------------------------------')

# you can get the array representation and index object of the Series via its values and index attribute
print('obj.values =', obj.values)
print('obj.index =', obj.index)

0    4
1    7
2   -5
3    3
dtype: int64
----------------------------------------
obj.values = [ 4  7 -5  3]
obj.index = RangeIndex(start=0, stop=4, step=1)


In [4]:
# often it will be desirable to create a Series with an index identifying each data point with a label
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)
print('----------------------------------------')
print('obj.index =', obj2.index)

d    4
b    7
a   -5
c    3
dtype: int64
----------------------------------------
obj.index = Index(['d', 'b', 'a', 'c'], dtype='object')


In [5]:
# compared with Numpy arrays, you can use labels in the index when selecting single value or a set of values
print("obj2['a'] =", obj2['a'])
print("obj2['d'] =", obj2['d'])
print('----------------------------------------')
print("obj2[['c', 'a', 'd']] =")
print(obj2[['c', 'a', 'd']])

obj2['a'] = -5
obj2['d'] = 4
----------------------------------------
obj2[['c', 'a', 'd']] =
c    3
a   -5
d    4
dtype: int64


In [6]:
# using Numpy functions or Numpy-like operations, will preserve the index-value link
print("obj2[obj2 > 0] =")
print(obj2[obj2 > 0])
print('----------------------------------------')
print("obj2 * 2 =") 
print(obj2 * 2)
print('----------------------------------------')
print("np.exp(obj2) =")
print(np.exp(obj2))
print('----------------------------------------')

obj2[obj2 > 0] =
d    4
b    7
c    3
dtype: int64
----------------------------------------
obj2 * 2 =
d     8
b    14
a   -10
c     6
dtype: int64
----------------------------------------
np.exp(obj2) =
d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64
----------------------------------------


In [7]:
# another way to think about a Series is a fixed-length, ordered dict
# it can be used in many contexts where you might use a dict
print('b' in obj2)
print('e' in obj2)

True
False


In [8]:
# if you have data contained in a Python dict
# you can create a Series from it by passing the dict

sdata ={'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [9]:
# you can pass in the list of index along with a dict to override the creation of Series
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [10]:
# the isnull() and notnull() functions in pandas should be used to detect missing data
print('pd.isnull(obj4) =')
print(pd.isnull(obj4)) # or obj4.isnull()
print('----------------------------------------')
print('pd.notnull(obj4) =')
print(pd.notnull(obj4)) # or obj4.notnull()
print('----------------------------------------')

pd.isnull(obj4) =
California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool
----------------------------------------
pd.notnull(obj4) =
California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool
----------------------------------------


In [11]:
# a useful Series feature for many applications is that 
# it automatically aligns by index label in arithmetic operations

print('obj3 =')
print(obj3)
print('----------------------------------------')
print('obj4 =')
print(obj4)
print('----------------------------------------')
print('obj3 + obj4 =')
print(obj3 + obj4)
print('----------------------------------------')


obj3 =
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
----------------------------------------
obj4 =
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
----------------------------------------
obj3 + obj4 =
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64
----------------------------------------


In [12]:
# both the Series and its index have a 'name' attribute
# which integrates with other keys areas of pandas functionality

obj4.name = 'population'
obj4.index.name = 'state'

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [13]:
# a Series's index can be altered in-place by assignment
print(obj)
print('----------------------------------------')
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print(obj)
print('----------------------------------------')


0    4
1    7
2   -5
3    3
dtype: int64
----------------------------------------
Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64
----------------------------------------


## 5.1.2 DataFrame

In [14]:
# a DataFrame represents a rectangular table of data 
# and contains an ordered collection of columns, each of which can be a different value type

# the DataFrame has both a row and column index
# it can be thought of as a dict of Series all sharing the same index

# there are many ways to construct a DataFrame
# though one of the most common is from a dict of equal-length list or Numpy arrays

data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year' : [2000, 2001, 2002, 2001, 2002, 2003],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [15]:
# for large DataFrames, the head() or tail() methods select the first (or last) five rows
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [16]:
# if you specify a sequence of columns, the DataFrame's columns will be arranged in that order
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [17]:
# if you pass a column that isn't contained in the dict, it will appear with missing values in the result
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [18]:
# a column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute
print(frame2['state'])
print('----------------------------------------')
print(frame2.year)
print('----------------------------------------')


one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object
----------------------------------------
one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64
----------------------------------------


In [19]:
# rows can also be retrieved by position or name with the special loc[] attribute
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [20]:
# columns can be modified by assignment
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [21]:
# when you assign lists or arrays to a column, the value's length must match the length of the DataFrame
# if you assign a Series, its labels will be realigned exactly to the DataFrame's index, inserting missing values

val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [22]:
# assigns a column that doesn't exist creates a new column
# the del keyword will delete columns as with a dict

frame2['eastern'] = frame2.state == 'Ohio'
print(frame2)
print('----------------------------------------')

del frame2['eastern']
print(frame2)
print('----------------------------------------')

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False
----------------------------------------
       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN
----------------------------------------


In [23]:
# another common form of data is a nested dict of dicts
# pandas will interpret the outer dict keys as the columns and the inner keys as the rows indices

pop = {'Nevada' : {2001 : 2.4, 2002 : 2.9},
       'Ohio' : {2000 : 1.5, 2001 : 1.7, 2002 : 3.6}}

frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [24]:
# you can transpose the DataFrame with similar syntax to a Numpy array (using the .T attribute)

frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [25]:
# dict of Series are treated in much the same way

pdata = {'Ohio' : frame3['Ohio'][:-1],
         'Nevada' : frame3['Nevada'][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [26]:
# if a DataFrame's 'index' and 'columns' have their 'name' attribtue set, these will also be displayed

frame3.index.name = 'year'
frame3.columns.name = 'state'

frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [27]:
# as with Series, the 'values' attribute returns the data contained in the DataFrame as a two-dimensional array

frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [28]:
# if the DataFrame's columns are different dtypes
# the dtype of the values array will be chosen to accomodate all of the columns

frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 5.1.3 Index Object

In [29]:
# pandas's Index Object are responsible for holding the axis labels and other metadata (like axis name or names)
# any sequence of labels you use when constructing a Series or DataFrame is internally converted to an Index

obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

# Index Object are immutable and thus can't be modified by the user
# index = 'd' # TypeError

Index(['a', 'b', 'c'], dtype='object')

In [30]:
# Immutability makes it safer to share Index Object among data structures
labels = pd.Index(np.arange(3))
print('labels =', labels)
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
print('----------------------------------------')
print('obj2 =')
print(obj2)
print('----------------------------------------')
print(obj2.index is labels)

labels = Int64Index([0, 1, 2], dtype='int64')
----------------------------------------
obj2 =
0    1.5
1   -2.5
2    0.0
dtype: float64
----------------------------------------
True


In [31]:
# in addition to being array-like, an Index also behaves like a fixed-size set

print('frame3.columns =', frame3.columns)
print('----------------------------------------')
print('frame3.index =', frame3.index)
print('----------------------------------------')
print('Ohio' in frame3.columns)
print(2003 in frame3.index)

frame3.columns = Index(['Nevada', 'Ohio'], dtype='object', name='state')
----------------------------------------
frame3.index = Int64Index([2001, 2002, 2000], dtype='int64', name='year')
----------------------------------------
True
False


In [32]:
# unlike Python set, a pandas Index can contain duplicate labels

dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 5.2 Essential Functionality

## 5.2.1 Reindexing

In [33]:
# an important method on pandas objects is reindex()
# which mean create a new object from the data conformed to a new index using reindex()

obj  = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print('obj =')
print(obj)
print('----------------------------------------')

# calling reindex() on Series rearanges the data according to the new index
# introducing missing values if any index values were not already present

obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print('obj2 =')
print(obj2)
print('----------------------------------------')

obj =
d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
----------------------------------------
obj2 =
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64
----------------------------------------


In [34]:
# for ordered data like time series, it may be desirable to do some interpolation or filling of values when reindexing
# the 'method' argument allows us to do this
# bthe ffill() method helps foward-fills the values

# create data

obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print('obj3')
print(obj3)
print('----------------------------------------')
print("obj3.reindex(range(6), method='ffill') =")
print(obj3.reindex(range(6), method='ffill'))
print('----------------------------------------')


obj3
0      blue
2    purple
4    yellow
dtype: object
----------------------------------------
obj3.reindex(range(6), method='ffill') =
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object
----------------------------------------


In [35]:
# with DataFrame, reindex() can alter either the (row) index, columns, or both

#create data
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [36]:
# when passed only a sequence, it reindex the rows (indexes) in the result

frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [37]:
# the columns can be reindex using the 'columns' argument

states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 5.2.2 Dropping Entries from an Axis

In [38]:
# the drop() method will return a new object with the indicated value or values deleted from an axis

#create data
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
print('obj =')
print(obj)
print('----------------------------------------')
print("obj.drop('c') =") 
print(obj.drop('c'))
print('----------------------------------------')
print("obj.drop(['d', 'c']) =")
print(obj.drop(['d', 'c']))
print('----------------------------------------')

obj =
a    0
b    1
c    2
d    3
e    4
dtype: int32
----------------------------------------
obj.drop('c') =
a    0
b    1
d    3
e    4
dtype: int32
----------------------------------------
obj.drop(['d', 'c']) =
a    0
b    1
e    4
dtype: int32
----------------------------------------


In [39]:
# with DataFrame, index values can be deleted from either axis

# create data
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four']
                   )
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [40]:
# calling drop() with a sequence of labels will drop values from the row labels (default: axis=0)

data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [41]:
# you can drop values from the columns by passing axis=1 or axis='columns'

data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [42]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [43]:
# many functions, like drop(), which modify the size or shape of a Series or DataFrame, can have an 'inplace' option

obj.drop('c', inplace=True)
obj

a    0
b    1
d    3
e    4
dtype: int32

## 5.2.3 Indexing, Selection and Filtering

In [44]:
# Series indexing (obj[...]) works analogously to Numpy array indexing
# except you can use Series's index values instead of only integers

# create dada
obj = pd.Series(np.arange(4), index=['a', 'b', 'c', 'd'])
print(obj)
print('----------------------------------------')
print("obj['b'] =", obj['b'])
print('----------------------------------------')
print("obj[1] =", obj[1])
print('----------------------------------------')
print("obj[['b', 'a', 'd']] =")
print(obj[['b', 'a', 'd']])
print('----------------------------------------')
print("obj[2:4] =")
print(obj[2:4])
print('----------------------------------------')
print("obj[[1, 3]] =")
print(obj[[1, 3]])
print('----------------------------------------')

a    0
b    1
c    2
d    3
dtype: int32
----------------------------------------
obj['b'] = 1
----------------------------------------
obj[1] = 1
----------------------------------------
obj[['b', 'a', 'd']] =
b    1
a    0
d    3
dtype: int32
----------------------------------------
obj[2:4] =
c    2
d    3
dtype: int32
----------------------------------------
obj[[1, 3]] =
b    1
d    3
dtype: int32
----------------------------------------


In [45]:
# using boolean array
print("obj[obj < 2] =")
print(obj[obj < 2])
print('----------------------------------------')

# slicing with labels behaves differently than normal Python slicing in that: the end point is INCLUSIVE
print("obj['b':'d'] =")
print(obj['b':'d'])
print('----------------------------------------')

# setting using these methods modifies the corresponding section of the Series
obj['b':'c'] = 5
print('obj =')
print(obj)
print('----------------------------------------')

obj[obj < 2] =
a    0
b    1
dtype: int32
----------------------------------------
obj['b':'d'] =
b    1
c    2
d    3
dtype: int32
----------------------------------------
obj =
a    0
b    5
c    5
d    3
dtype: int32
----------------------------------------


In [46]:
# indexing into a DataFrame is for retrieving one or more columns either with a single value or sequence

# create data
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four']
                   )
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [47]:
# passing a single element select a column

data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [48]:
# passing a list of elements select columns

data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [49]:
# slicing [begin:end:step, begin:end:step, ...]

data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [50]:
# select data with a boolean array

data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [51]:
data[data < 5] = 0

data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## 5.2.4 Selection with loc and iloc

### select a subset from a DataFrame using: axis labels (loc)

In [52]:
#display the data

data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [53]:
# remember that slicing with labels include the endpoint

data.loc['Colorado', ['two', 'three']] # return a Series

two      5
three    6
Name: Colorado, dtype: int32

In [54]:
# it can also work with slices

data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

### select a subset from a DataFrame using: integers (iloc)

In [55]:
# display the data

data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [56]:
data.iloc[2, [3, 0, 1]] # return a Series

four    11
one      8
two      9
Name: Utah, dtype: int32

In [57]:
data.iloc[2] # return a Series

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [58]:
data.iloc[[1, 2], [3, 0, 1]] # return a dataFrame

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [59]:
data.iloc[:, :3][data.three > 5] # selection combine with filtering data

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## 5.2.5 Integer Indexes

In [60]:
# working with pandas objects indexed by integers is something that often trips up new users 
# due to some differences with indexing semantics on built-in Python data structures like lists and tuples

ser = pd.Series(np.arange(3.))
ser

# ser[-1] # (will generate error)

# will generate an error because you use integer index
# this makes the interpreter has a hard time inferring what you want (label-based or position-based)
# basically it doesn't know whether to find index = -1 or index = 2 in this situation

# to keep things consistent:
# if you have an index axis containing integers, data selection will always be label-oriented
# so index = -1 in this case, which there are no available values => raise an error

0    0.0
1    1.0
2    2.0
dtype: float64

In [61]:
# create data

ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
print('ser2 =')
print(ser2)
print('----------------------------------------')
print('ser2[-1] =', ser2[-1]) # this is fine because you use label-base
print('----------------------------------------')
print('ser[:1] =')
print(ser[:1]) # position-slicing so the endpoint is exclusive
print('----------------------------------------')

# for more precision, use loc[] or iloc[]
print('ser.loc[:1] =')
print(ser.loc[:1])  # label-slicing also include the endpoint
print('----------------------------------------')
print('ser.iloc[:1] =') 
print(ser.iloc[:1]) # position-slicing exclude the endpoint
print('----------------------------------------')

ser2 =
a    0.0
b    1.0
c    2.0
dtype: float64
----------------------------------------
ser2[-1] = 2.0
----------------------------------------
ser[:1] =
0    0.0
dtype: float64
----------------------------------------
ser.loc[:1] =
0    0.0
1    1.0
dtype: float64
----------------------------------------
ser.iloc[:1] =
0    0.0
dtype: float64
----------------------------------------


## 5.2.6 Arithmetic and Data Alignment

In [62]:
# create data
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

print('s1 =')
print(s1)
print('----------------------------------------')
print('s2 =')
print(s2)
print('----------------------------------------')

s1 =
a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
----------------------------------------
s2 =
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64
----------------------------------------


In [63]:
# when you adding together objects, if any index pairs are not the same
# the respective index in the result will be the UNION of the index pairs

s1 + s2 # the internal data alignment introduces missing values in the label locations that don't overlap

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [64]:
# create data

df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                   columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado']
                  )
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [65]:
# create data

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                   columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon']
                  )
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [66]:
# in the case of DataFrame, alignment is performed on both the rows and the columns

# adding these together returns a DataFrame whose index and columns are the UNIONs of the ones in each DataFrame
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [67]:
# if you add DataFrame objects with no columns or row labels in common, the result will contain all nulls

df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

df1 + df2

A   B
0 NaN NaN
1 NaN NaN

## 5.2.7 Arithmetic methods with fill values

In [68]:
# create data
df1 = pd.DataFrame(np.arange(12.).reshape(3, 4),
                   columns=list('abcd')
                  )
# display data
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [69]:
# create data
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5),
                   columns=list('abcde')
                   )
df2.loc[1, 'b'] = np.nan

# display data
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [70]:
df1 + df2 # adding these together will result in NaN values in locations that don't overlap

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [71]:
# using the add() method on df1, pass df2 and an argument to fill_value

df1.add(df2, fill_value=0) # likes df1 + df2, but now no NaN values

# pd.DataFrame.add(df1, df2, fill_value=0) provides the same result

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [72]:
# some arithmetic methods have an inverse counterpart (with names start with 'r') that has arguments flipped

df1.rdiv(1)  # same as 1 / df1

# pd.DataFrame.rdiv(df1, 1) provides the same result


a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [73]:
# relatedly, when reindexing a Series or DataFrame, you can also specify a different fill value

df1.reindex(columns=df2.columns, fill_value=0.)

a    b     c     d    e
0  0.0  1.0   2.0   3.0  0.0
1  4.0  5.0   6.0   7.0  0.0
2  8.0  9.0  10.0  11.0  0.0

## 5.2.8 Operations between DataFrame and Series

In [74]:
# As with Numpy arrays of different dimension, arithmetic between DataFrame and Series is also defined

# Example with NUMPY ARRAYS' arithmetic operations

# create data
arr = np.arange(12.).reshape((3, 4))
print('arr =')
print(arr)
print('----------------------------------------')
print('arr[0] =')
print(arr[0])
print('----------------------------------------')
print('arr - arr[0] =')
print(arr - arr[0])  # different between an array and one of its rows
print('----------------------------------------')

arr =
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
----------------------------------------
arr[0] =
[0. 1. 2. 3.]
----------------------------------------
arr - arr[0] =
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]
----------------------------------------


In [75]:
# the operation above is performed once per row (broadcasting)
# Operations between DataFrame and Series are similar

frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon']
                    )

frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [76]:
series = frame.iloc[0]

series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [77]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [78]:
# if an index is not found in either the DataFrame's columns or the Series's index
# the objects will be reindexed to form a UNION

series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [79]:
frame + series2 

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [80]:
# if you want to broadcast over the columns, matching on the rows, you have to use an arithmetic method

# display data
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [81]:
series3 = frame['d']

series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [82]:
frame.sub(series3, axis=0) # you can also type axis='index'

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 5.2.9 Function Application and Mapping

In [83]:
# NumPy ufuncs also work with pandas objects

# create data 
frame = pd.DataFrame(np.random.randn(4, 3), 
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon']
                    )

frame

b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [84]:
# get absolute values
np.abs(frame)

b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

In [85]:
# another frequent operation is applying a function on one-dim arrays to each column or row
# DataFrame's apply() method does exactly this

f = lambda x : x.max() - x.min()
frame.apply(f) # default: axis=0 (or axis='index') -> per column

b    1.802165
d    1.684034
e    2.689627
dtype: float64

In [86]:
frame.apply(f, axis='columns') # (or axis=1) -> per row

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

In [87]:
# the function passed to apply need not return a scalar value; it can also return a Series

def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [88]:
# loop through every column and find max, min

frame.apply(f)

b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

In [89]:
# element-wise Python functions can be used, too

_format = lambda x: '%.2f' % x # 2 decimal place

In [90]:
# display data
frame

b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [91]:
# applymap() is a DataFrame method that apply element-wise functions
frame.applymap(_format)

b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

In [92]:
# map() is a Series method that apply element-wise functions
frame['e'].map(_format)

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

## 5.2.10 Sorting and Ranking

### Use the sort_index() method to sort lexicographically by row or column index

In [93]:
# create data
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [94]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [95]:
# with a DataFrame, you can use sort_index() on either axis

# create data
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c']
                    )

frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [96]:
frame.sort_index() # axis=0 (default)

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [97]:
frame.sort_index(axis='columns') # or axis=1

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [98]:
frame.sort_index(axis=1, ascending=False) # sort in descending order

d  c  b  a
three  0  3  2  1
one    4  7  6  5

### Use sort_value() method to sort by values

In [99]:
# create data
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [100]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [101]:
# create data
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values() # any Missing values are sorted to the end of the Series by default

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [102]:
obj.sort_values(ascending=False)

2    7.0
0    4.0
5    2.0
4   -3.0
1    NaN
3    NaN
dtype: float64

In [103]:
# when sorting a DataFrame, you can use the data in one or more columns as the sort keys

# create data
frame = pd.DataFrame(
    {
        'b' : [4, 7, -3, 2],
        'a' : [0, 1, 0, 1]
    }
)

frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [104]:
frame.sort_values(by='b') # pass in the columns used to sort the DataFrame

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [105]:
frame.sort_values(by=['a', 'b']) # pass a list to sort by multiple columns 
# (here a comes first so 'a' is prioritise over 'b')

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

### Ranking

In [106]:
# ranking assigns ranks from one through the number of valid data points in an array

# create data
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [107]:
obj.rank() # method='average' (default) is used to breaks ties

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [108]:
obj.rank(method='first') # breaks ties using their order

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [109]:
# you can rank in descending order, too

obj.rank(ascending=False, method='max') # break ties by assigning all tie values the highest rank in the group

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [110]:
# DataFrame can compute ranks over the rows or the columns

# create data
frame = pd.DataFrame(
    {
        'b' : [4.3, 7, -3, 2],
        'a' : [0, 1, 0, 1],
        'c' : [-2, 5, 8, -2.5]
    }
)

frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [111]:
frame.rank(axis='columns', method='max')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [112]:
frame.rank(axis='index', method='min')

b    a    c
0  3.0  1.0  2.0
1  4.0  3.0  3.0
2  1.0  1.0  4.0
3  2.0  3.0  1.0

## 5.2.11 Axis Indexes with Duplicate Labels

In [113]:
# create data 
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [114]:
# The index's is_unique property can tells you whether its labels are unique or not
print(obj.index.is_unique)
print('----------------------------------------')
# indexing labels with multiple entries return a Series
print(obj['a'])
print('----------------------------------------')
# while indexing labels with a single entry return a scalar value
print(obj['c'])

False
----------------------------------------
a    0
a    1
dtype: int64
----------------------------------------
4


In [115]:
# same logic extends to indexing rows in a DataFrame

# create data
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'c', 'b', 'b'])
df

0         1         2
a  0.274992  0.228913  1.352917
c  0.886429 -2.001637 -0.371843
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

In [116]:
# indexing labels with multiple entries return a DataFrame
df.loc['b']

0         1         2
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

In [117]:
# while indexing labels with a single entry return a Series
df.loc['a']

0    0.274992
1    0.228913
2    1.352917
Name: a, dtype: float64

# 5.3 Summarizing and Computing Descriptive Statistics

In [118]:
# create data
df = pd.DataFrame(
    [
        [1.4, np.nan], 
        [7.1, -4.5],
        [np.nan, np.nan],
        [0.75, -1.3]
    ],
    index=['a', 'b', 'c', 'd'],
    columns=['one', 'two']
)

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [119]:
# calling DataFrame's sum() method returns a Series containing sums

df.sum() # axis=0 (default)

one    9.25
two   -5.80
dtype: float64

In [120]:
df.sum(axis='columns') # skipna=True (default)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [121]:
df.sum(axis='columns', skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [122]:
# some methods, like idxmin() and idxmax(), return indirect statistics

df.idxmax()

one    b
two    d
dtype: object

In [123]:
# accumulation methods

df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [124]:
# describe() produces multiple summary statistics in one shot

df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [125]:
# on non-numeric data, describe() produces alternative summary statistics

# create data
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## 5.3.1 Correlation and Covariance

In [126]:
# use the pandas_datareader module to download some data for a few stock tickers
import pandas_datareader.data as web

In [127]:
# get stock data for APPLE, IBM, MICROSOFT, GOOGLE
all_data = {ticker : web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [128]:
# get the adj close price for those stocks
price = pd.DataFrame({ticker : data['Adj Close']
                      for ticker, data in all_data.items()})

In [129]:
# get the volume for those stocks
volume = pd.DataFrame({ticker : data['Volume']
                      for ticker, data in all_data.items()})

In [130]:
# create data
returns = price.pct_change()

In [131]:
returns.tail() # like head() but opposite end

AAPL       IBM      MSFT      GOOG
Date                                              
2022-03-08 -0.011676 -0.003094 -0.010971  0.006437
2022-03-09  0.034997  0.004297  0.045858  0.051757
2022-03-10 -0.027186 -0.014815 -0.010087 -0.008845
2022-03-11 -0.023909 -0.003136 -0.019328 -0.016630
2022-03-11  0.000000  0.000000  0.000000  0.000000

In [132]:
# corr() methods of Series compute the correlation of the overlapping
returns['MSFT'].corr(returns['IBM'])

0.48088572382813266

In [133]:
# cov() methods computes the covariance
returns['MSFT'].cov(returns['IBM'])

0.00014284479553010416

In [134]:
# DataFrame's corr() and cov() return a full correlation or covariance matrix as a DataFrame
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.428982  0.744945  0.663878
IBM   0.428982  1.000000  0.480886  0.454590
MSFT  0.744945  0.480886  1.000000  0.784524
GOOG  0.663878  0.454590  0.784524  1.000000

In [135]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000378  0.000139  0.000257  0.000226
IBM   0.000139  0.000280  0.000143  0.000133
MSFT  0.000257  0.000143  0.000315  0.000244
GOOG  0.000226  0.000133  0.000244  0.000307

In [136]:
# using DataFrame's corrwith() method, you can compute pairwise correlations
# between a DataFrame's columns or rows with another Series or DataFrame

returns.corrwith(returns['IBM'])

AAPL    0.428982
IBM     1.000000
MSFT    0.480886
GOOG    0.454590
dtype: float64

In [137]:
# passing a DataFrame computes the correlations of matching columns names
returns.corrwith(volume) # axis=0 (default)

AAPL   -0.081456
IBM    -0.128977
MSFT   -0.070134
GOOG   -0.094544
dtype: float64

## 5.3.2 Unique values, Values counts, and Membership

In [138]:
# create data
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

# unique() method create a new collection with unique value
uniques = obj.unique()

# display data
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [139]:
# values_counts() method counts values in the collection

obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [140]:
# value_counts also available as a top-level pandas function

pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [141]:
# display data
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [142]:
# isin() method perform vectorized set membership check

mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [143]:
# you can use it to filter data
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [144]:
# create data
data = pd.DataFrame(
    {
        'Qu1' : [1, 3, 4, 3, 4],
        'Qu2' : [2, 3, 1, 2, 3],
        'Qu3' : [1, 5, 2, 4, 4]
    }
)

data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [145]:
# passing pd.value_counts into the apply() functions let you compute a histogram on multiple related columns in a DataFrame

result = data.apply(pd.value_counts).fillna(0) # axis=0 (default)

result # show the number of time a value appear in each column (can be used to draw a histogram)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0